/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    DetailsDialog: typeof import('./components/DetailsDialog.vue')['default']
    Hint: typeof import('./components/Hint.vue')['default']
    ListSnackBar: typeof import('./components/ListSnackBar.vue')['default']
    Notification: typeof import('./components/ui/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    TableFilterForm: typeof import('./components/TableFilterForm.vue')['default']
    ToggleTheme: typeof import('./components/ui/ToggleTheme.vue')['default']
    UserModal: typeof import('./components/UserModal.vue')['default']
  }
}
