/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CargoModal: typeof import('./components/CargoModal.vue')['default']
    CityModal: typeof import('./components/CityModal.vue')['default']
    ClientModal: typeof import('./components/ClientModal.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    CountryModal: typeof import('./components/CountryModal.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    Hint: typeof import('./components/Hint.vue')['default']
    ListSnackBar: typeof import('./components/ListSnackBar.vue')['default']
    Notification: typeof import('./components/ui/Notification.vue')['default']
    PaymentModal: typeof import('./components/PaymentModal.vue')['default']
    PriceModal: typeof import('./components/PriceModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    TableFilterForm: typeof import('./components/TableFilterForm.vue')['default']
    ToggleTheme: typeof import('./components/ui/ToggleTheme.vue')['default']
    TruckModal: typeof import('./components/TruckModal.vue')['default']
    UserModal: typeof import('./components/UserModal.vue')['default']
    WarehouseModal: typeof import('./components/WarehouseModal.vue')['default']
  }
}
