/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/City': RouteRecordInfo<'/City', '/City', Record<never, never>, Record<never, never>>,
    '/Client': RouteRecordInfo<'/Client', '/Client', Record<never, never>, Record<never, never>>,
    '/Country': RouteRecordInfo<'/Country', '/Country', Record<never, never>, Record<never, never>>,
    '/Dictionary': RouteRecordInfo<'/Dictionary', '/Dictionary', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Role': RouteRecordInfo<'/Role', '/Role', Record<never, never>, Record<never, never>>,
    '/Truck': RouteRecordInfo<'/Truck', '/Truck', Record<never, never>, Record<never, never>>,
    '/Warehouse': RouteRecordInfo<'/Warehouse', '/Warehouse', Record<never, never>, Record<never, never>>,
  }
}
